services:
  favorite_literature_moderation_database:
    container_name: moderation_db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "fav_lit_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8000:5432"